### ISSUE TITLE
Minotaurus invisible in server game.  [Bug]: 

### ISSUE THREAD

**Issue by cajlo** [Silentine/GrimoireOfGaia#212] opened 2023-12-07 19:31 UTC
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.7.2

### Mod version

14.23.5.2860

### Java version

8.282

### Issue Description

Minotaurus invisible in server game. Minotaur is ok. It can be fixed by reload server, but need many-many attempts

**Comment by Mrbysco** [comment] 2023-12-07 20:15
Duplicate of #173

**Closed as completed by Mrbysco** 2023-12-07 20:15 UTC
Labels: bug, duplicate
