### ISSUE TITLE
[Bug]: Bomber goblin crash the game.

### ISSUE THREAD

**Issue by mihaaairu** [Silentine/GrimoireOfGaia#183] opened 2022-08-07 13:09 UTC
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.54

### Mod version

2.0.0-alpha.13

### Java version

Java 8 Update 321

### Issue Description

World stops when bomber-goblin starting to explode. (gaia.entity.GoblinFeral.m_8107_(GoblinFeral.java:159)). Btw, i can reenter the world and turn peacefull mode ON as fast as i can, but it's kinda bad way to solve the problem. I could turn spawning them off, but it's bad decision too/

### Additional Information

Here it is the crash-log in readable format. 
https://pastebin.com/rAbNMX3k

**Comment by Mrbysco** [comment] 2022-08-07 15:22
I'm unable to reproduce this issue.
Could you provide the latest.log from when it happens? There's so many mods that the crash-log is barely readable as many mods are mixin into entity stuff

**Comment by Mrbysco** [comment] 2022-08-12 15:34
Should be fixed in alpha 14

**Closed as completed by Mrbysco** 2022-08-12 15:34 UTC
Labels: bug, 1.18.2
