### ISSUE TITLE
Some mob's weapon are invisible 

### ISSUE THREAD

**Issue by MokoBlack** [Silentine/GrimoireOfGaia#106] opened 2018-12-03 14:41 UTC
Is it a bug?

**Comment by Silentine** [comment] 2018-12-03 22:21
I don't know how to answer that question. 

First, what mobs have invisible weapons? Second, how do you know they have invisible weapons? Perhaps they never had weapons equipped in the first place? Please use and fill-in the **bug report form** next time.

It is the same as asking the question "Game crashes when the mod is installed, why?". How can I answer the question without any details on how or why it crashed without a crash log or a way to reproduce it?

**Comment by MokoBlack** [comment] 2018-12-04 01:40
oh sorry for my poor English... i have'n see the rule
forget it friend

**Comment by MokoBlack** [comment] 2018-12-04 02:59
![image](https://user-images.githubusercontent.com/43997988/49416060-a7ba2100-f7b3-11e8-860a-f0e50f40b4c0.png)

**Comment by Silentine** [comment] 2018-12-14 14:33
> 
> 
> oh sorry for my poor English... i haven't see the ruler
> yes, they never had weapons equipped in the first place
> ![image](https://user-images.githubusercontent.com/43997988/49415819-d388d700-f7b2-11e8-86bc-7e7d3a0108de.png)

They have a 50% chance to spawn equipped with a Broom.

> 
> 
> ![image](https://user-images.githubusercontent.com/43997988/49416060-a7ba2100-f7b3-11e8-860a-f0e50f40b4c0.png)

They have a 25% chance to spawn equipped with a Fan. I'm not sure if the arm pose is an animation glitch or a timed pose.

**Comment by Silentine** [comment] 2019-03-10 14:29
The Nine-Tails arm posing was caused by an animation glitch, not because it was holding an invisible fan.
Fixed in 1.6.9.

**Closed by Silentine** 2019-03-10 14:29 UTC
Labels: needs verification
