### ISSUE TITLE
[Suggestion]: 1.16.5?

### ISSUE THREAD

**Issue by LisitaDarkin** [Silentine/GrimoireOfGaia#199] opened 2023-04-03 22:19 UTC
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Hi, I was playing with this mod on 1.12.2, I changed to 1.16.5 and I was looking for it for that version and I couldn't find it... will there be any update or port for 1.16.5?

**Comment by Mrbysco** [comment] 2023-04-03 22:46
Duplicate of #198

**Closed as completed** 2023-04-03 22:47 UTC
Labels: enhancement
