### ISSUE TITLE
Dedicated server crash upon player login

### ISSUE THREAD

**Issue by Febilian** [Silentine/GrimoireOfGaia#67] opened 2018-09-02 18:50 UTC
https://gist.github.com/Febilian/1eee519e05e1f25d49c78d586898452a

I updated the mod, recreated the config since it changed formatting, and it starts fine but as soon as I load into the world I get kicked shortly after - server closed. Something about item stacks and the Arachne mob, I guess?

This is the contents of my grimoireofgaia.cfg if it matters. It's consistent across server and client, and this was after attempting toggling enableSpawn to false to see if it made a difference(it didn't).

https://gist.github.com/Febilian/6f2a0db268387576beb097afe7672d93

**Comment by Mrbysco** [comment] 2018-09-02 19:06
This is due to the mod accidentally calling a client-side only method.

**Comment by Silentine** [comment] 2018-09-02 20:32
I suggest disabling the Arachne through the config by setting the spawn rate to 0 for now.

The line of code causing the issue is not suppose to be there. I completely forgot to remove it before release.

**Comment by Febilian** [comment] 2018-09-03 01:11
So it's just the Arachne doing that, then? Alright, I'll see how preventing its spawns goes.

**Comment by Silentine** [comment] 2018-09-04 12:08
This should now be fixed in the 1.6.0-beta4.

**Closed by Silentine** 2018-09-04 12:08 UTC
Labels: bug
